export const ComposablesAutoImport = {
  "@teranes/vue-composables": [
    "useGetAccessedProps",
    "useFunctionCaller",
    "useGetParameters",
    "useGetFromStorage",
    "useSetToStorage",
    "useStringTemplateWithReplacements",
    "usePaginate",
    "usePaginationHandler",
    "useFilter",
    "useFilterAndPaginate",
    "useIsNull",
    "useMapper",
    "useObjectAssign",
    "useCloneDeep",
    "useCoalesce",
    "useCoalesceTruthy",
    "useObjectValueByPath",
    "useVModel",

    "useDebounce",
    "useDraggable",
    "useInfiniteScroll",
    "useEventListener",
    "useIsEventInsideElement",
    "useThrottle",
  ],
};